image: docker:stable
variables:
  NAME: "interface-whatsapi"
  DIR_PATH: "/home/docker/"
stages:
  - logs
  - init_project
  - node
  - deploy

logs:
  stage: logs
  script:
    - echo "macinfo" | docker login --username=admin --password-stdin  https://docker.mactus.com.br:5000 || true
    - docker logs $NAME
  when: manual
  only:
    - master

init_project:
  stage: init_project
  script:
    - echo "macinfo" | docker login --username=admin --password-stdin  https://docker.mactus.com.br:5000 || true
    - docker rm -f $NAME || true
    - docker build . -t $NAME
    - docker run -d --name interface-whatsapi  -p 127.0.0.1:3000:3000 --restart always interface-whatsapi 
  when: manual
  only:
    - master

node:
  stage: node
  image: node:alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - ./
    expire_in: 1 week
  when: manual
deploy:
  variables:
    NAME: "interface-whatsapi"
    DIR_PATH: "/home/docker/"
  stage: deploy
  script:
    - cp -apr ./ $DIR_PATH/$NAME/node/
    - docker restart $NAME
  artifacts:
    paths:
      - ./
  when: manual

